### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by zwickerr** [BernhardWebstudio/DataShot_DesktopApp#10]
- [x] All fields and buttons should fit on one page to avoid scrolling.

- [x] Scrolling speed is too slow.

- [x] Scrolling does not work when mouse pointer is over one of the following fields: Collectors, Specimen Parts, Specimen Notes, and Numbers & more.

**Comment by GenieTim** [comment]
Only partially fixed: scrolling still does not work when mouse pointer is over one of the following fields: Collectors, Specimen Parts, Specimen Notes, and Numbers, as these fields have their own scrolling.

**Comment by GenieTim** [comment]
Fixed in 
[20552ca](https://github.com/BernhardWebstudio/DataShot_DesktopApp/commit/20552cad9dec548b7b28bba6ba48fe646b124f28)

**Comment by zwickerr** [comment]
On my computer the field sizes for Collectors, Specimen Parts, and Numbers & more are still larger than necessary.
I have attached a screenshot of the program running in full screen so you can see how much space there is on our displays.

![ScreenshotFieldSizes1-9-3](https://user-images.githubusercontent.com/56917842/67663309-7b783780-f965-11e9-872b-00e007d7671d.png)

**Comment by GenieTim** [comment]
I propose you add `editor.fields.maxHeight=50` to the imagecapture.properties (for the upcoming version, available for now as Pre-release) and adjust the value of 50 untill it suits your needs. Feel free to tell me which value works best for you, so I can set it as default for other users.

**Comment by zwickerr** [comment]
Thanks for the fixes. A maxHeight of 70 works best.
