### ISSUE TITLE
Opening Specimens

### ISSUE THREAD

**Issue by zwickerr** [BernhardWebstudio/DataShot_DesktopApp#11]
After a while, specimens can not be opened anymore from the search results, until DataShot is restarted. 

[imagecapture191024-1123.log](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/3766706/imagecapture191024-1123.log)
[imagecapture191024-1203.log](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/3766887/imagecapture191024-1203.log)
[imagecapture191024-1325.log](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/3767244/imagecapture191024-1325.log)
[imagecapture191024-1650.log](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/3768175/imagecapture191024-1650.log)
[imagecapture191024-1703.log](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/3768236/imagecapture191024-1703.log)
[imagecapture191025-1016.log](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/3771069/imagecapture191025-1016.log)
[imagecapture191025-1045.log](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/3771192/imagecapture191025-1045.log)
[imagecapture191025-1453.log](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/3772119/imagecapture191025-1453.log)
[imagecapture191025-1647.log](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/3772594/imagecapture191025-1647.log)

**Comment by GenieTim** [comment]
Thanks for the log. Unfortunately, I cannot replicate this issue and I do not find anything suspicious in the log files. What is meant with "can not be opened anymore" - does "next" & "previous" still work, or just the "edit" button in the results list? Does other functionality work? Does it work when searching for something else?

**Comment by zwickerr** [comment]
When clicking the edit button, the mouse pointer shows a loading animation but the specimen never opens. When using the Next or Previous buttons the area for data entry turns gray, with no fields shown.
I will try if searching for something else works when it happens again.

**Comment by zwickerr** [comment]
- In 1.9.3, clicking the Next and Previous buttons stops doing anything at all.

- I can still enter text into the fields. When trying to save however, the following error is shown: "Error. Transaction already active".

- The Edit button in the search results still behaves the same, with the mouse pointer showing a loading animation.

- Searching for something else does not work either. The old list of results remains.

**Comment by GenieTim** [comment]
Thank you very much for the clarifications. I now found in the logs a possible issue: external edit of the Specimen in at least one case. In any case, the error handling was not suitable in the place where that one should have been caught, possibly other errors could lead to a crash there. Might be fixed in the current pre-release.

**Comment by GenieTim** [comment]
May I ask you to test with 1.9.4 and close the issue if it is resolved?

**Comment by zwickerr** [comment]
So far it seems to be working. In 1.9.3 sometimes I had to log in again. This is gone now as well. I will reopen the issue if the issue appears again once I can use "Copy prev" again.
