### ISSUE TITLE
Switching Between Image Sections

### ISSUE THREAD

**Issue by zwickerr** [BernhardWebstudio/DataShot_DesktopApp#12]
When selecting a different section of the image (e.g. PinLables) while zoomed in on FullImage, the division between the text entry fields and the picture changes. The area for text entry becomes too narrow and can not be changed back.

**Comment by GenieTim** [comment]
The new version should allow you (resp. @Commodore95) to resize the two sides to whatever size is fine. Additionally, to persisit a certain preference of side proportions, one can add `editor.window.division=0.5` to imagecapture.properties, resp. replace the 0.5 with whatever side proportions are preferred. As values, one might use something between 0 and 1, where 0 means only image, 1 means only fields and e.g. 0.5 means both sides same size.
