### ISSUE TITLE
Datum Returns to Default

### ISSUE THREAD

**Issue by zwickerr** [BernhardWebstudio/DataShot_DesktopApp#13]
The Datum field in Georeference returns to the default value WSG84 as soon as Georeference is opened again.

**Comment by GenieTim** [comment]
This was indeed a by Althea Parker hard coded value. Therfore, it is possible that using the upcoming version will lead to an aproportional amount of species with a datum "unknown", as this was still the default being saved into the database in some instances.

**Comment by GenieTim** [comment]
To be more precise, all instances preprocessed with elder versions than 1.9.3 will save "unknown" to the database when being preprocessed. The "WSG84" default was only set when having edited the Georeference. But there, it was set in any case, no matter what the value in the database was. This means, to comply with those elder versions, the decission has to be made: if there are no "unknown" dati in any case, they can be replaced with "WSG84" to restore this default. If there are cases, where "unknown" is correct, another solution has to be found. 
CC @ETHEntColl
