### ISSUE TITLE
Copy From Previous, Unable to Save

### ISSUE THREAD

**Issue by zwickerr** [BernhardWebstudio/DataShot_DesktopApp#17]
If "Copy prev" was used the specimen can not be saved anymore. The following error is shown: Error: Unable to save specimen ETHZ-ENT0164347.

If "Copy prev" is clicked multiple times, the entries in the lists "Determinations", "Collectors", and "Specimen Parts" are duplicated.

**Comment by GenieTim** [comment]
I am sorry that this one slipped through. I published an intermediate pre-release which might fix the issue.

Feel free to use elder versions in such cases, where things work, in order to still be productive, when the newest version is too new ;)

**Comment by zwickerr** [comment]
Thanks for the quick fix! It's working now.
