### ISSUE TITLE
Georeference Always Shows (1)

### ISSUE THREAD

**Issue by zwickerr** [BernhardWebstudio/DataShot_DesktopApp#20]
The "Georeference" button always shows (1), even when no values have been entered yet.

**Comment by GenieTim** [comment]
Kind of related to #13: the divergence between actual defaults between versions – as they were persisted in the database – makes it difficult to decide, what fields may be compared to decide whether we have default/empty or actual new values. 

In 1.10, the comparsion will be done against even less fields; this way, it works in _some_ (hopefully most) cases.
