### ISSUE TITLE
Coordinates cannot be removed

### ISSUE THREAD

**Issue by zwickerr** [BernhardWebstudio/DataShot_DesktopApp#23]
After deleting the coordinates the Georeference button still shows (1). When the Georef. is opened again, the coordinates reappear.

The issue occurs only when deleting the coordinates completely. If the coordinates are changed to different values they are saved correctly.

**Comment by GenieTim** [comment]
Is it possible that deleting georeference coordinates was impossible in elder (< 1.9) versions of DataShot too? If so, please make sure that resetting them is indeed a feature approved by @ETHEntColl :)
