### ISSUE TITLE
Ambigious filenumber 

### ISSUE THREAD

**Issue by Commodore95** [BernhardWebstudio/DataShot_DesktopApp#27]
Hallo Tim,

Das neue Release sieht soweit sehr gut aus.

Das Löschen von zuvor gespeicherten Zeilen läuft ohne Fehlermeldung ab.

Allerdings ist die Dateinummer dieselbe geblieben und es wäre gut, wenn diese Version eine eigene Dateinummer erhielte.

Ich melde mich falls es noch was gibt.

Gruss
David

**Comment by GenieTim** [comment]
Hi David

Besten Dank für Deine Rückmeldung. Die Nummer im Dateiname wird mit dem eigentlichen Release automatisch inkrementiert. Zugegebenermassen würde es Sinn ergeben, das vorher schon zu machen und ein `-beta` oder ähnlich anzuhängen. Ich werde sehen, ob sich das einfach in den Workflow integrieren lässt.

Beste Grüsse,

Tim

**Comment by Commodore95** [comment]
Hallo Tim

Ich komme hier bei etwas nicht weiter und zwar:

Wollte ich zu Übungszwecken eine Fibonacci Funktion in c# machen.

Allerdings kommt beim compilen ständig diese Fehlermeldung im Anhang.

Der Output path sollte allerdings richtig sein oder (Anhang“Output“)?

Ich habe noch den Code angehängt, da ich vermute, dass da irgendwo ein Anfängerfehler ist...

Wenn du mir damit helfen könntest, wäre ich dir unglaublich dankbar.

Beste Grüsse
David

**Comment by GenieTim** [comment]
Lieber David

Besten Dank für Deine Anfrage. Anhänge an E-Mails werden in GitHub issues nicht dargestellt. Bitte sende mir das E-Mail doch an meine [private E-Mail-Adresse](https://bernhard-webstudio.ch/index.php#contact). Ich wäre Dir sowieso dankbar, Probleme, die nichts mit DataShot zu tun haben, an meine [private E-Mail-Adresse](https://genieblog.ch/ueber-mich/) zu senden und für jeweils unterschiedliche Probleme neue Issues zu erstellen.

Beste Grüsse

Tim

**Comment by Commodore95** [comment]
Hallo Tim

Unten findest du die Korrespondenz bezüglich dem VPN- Datashot Problem.

Falls du mehr Informationen benötigst, lasse es mich wissen.

Freundliche Grüsse
David

From: Greeff Michael <michael.greeff@usys.ethz.ch>
Sent: Donnerstag, 19. März 2020 14:57
To: Sanchez David <dsanchez@ethz.ch>
Subject: Re: Datashot over VPN

Frage doch bitte mal Tim, was er davon hält...

Liebe Grüsse,
Michael


On 19 Mar 2020, at 14:48, Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>> wrote:

Hallo Michael

Wenn das Problem Datashot betrifft, dann müsste sich das Tim anschauen?

Gruss
David

From: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Sent: Donnerstag, 19. März 2020 14:47
To: Wartenburger Richard (ID SIS) <richard.wartenburger@id.ethz.ch<mailto:richard.wartenburger@id.ethz.ch>>; Scurtescu Cristian (ID BD) <cristian.scurtescu@id.ethz.ch<mailto:cristian.scurtescu@id.ethz.ch>>
Cc: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>; Parker Althea (ID SIS) <althea.parker@id.ethz.ch<mailto:althea.parker@id.ethz.ch>>
Subject: AW: Datashot over VPN

Lieber Herr Wartenburger

Die Verbindung von zu Hause über VPN Staff-net auf die DB klappt ohne Probleme. Nur die Applikation Datashot schafft es irgendwie nicht.
Hier der Status der Clients auf dem DB Server. Man sieht die VPN Verbindungen:
<image006.png>

Beste Grüsse
Hans Hirter

Von: Wartenburger Richard (ID SIS) <richard.wartenburger@id.ethz.ch<mailto:richard.wartenburger@id.ethz.ch>>
Gesendet: Donnerstag, 19. März 2020 13:13
An: Scurtescu Cristian (ID BD) <cristian.scurtescu@id.ethz.ch<mailto:cristian.scurtescu@id.ethz.ch>>; Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Cc: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>; Parker Althea (ID SIS) <althea.parker@id.ethz.ch<mailto:althea.parker@id.ethz.ch>>
Betreff: Re: Datashot over VPN

Hi all,

If you can connect from within the ETH network and not when using vpn, then I suspect that this is because the VPZ firewall rules do not allow you to connect from outside the VPZ, while you are setting up a vpn tunnel to the wrong network zone (most likely staff-net)?

Can you please send me the connection details you use to connect via vpn?
For example, I use the details below to connect to our id-sis zone (usng vpnc on Linux):

IPSec gateway sslvpn.ethz.ch<http://sslvpn.ethz.ch/>
IPSec ID id-sis
IPSec secret xxx
Xauth username richardw@id-sis.ethz.ch<mailto:richardw@id-sis.ethz.ch>

Best,
Richard
________________________________
From: Scurtescu Cristian (ID BD)
Sent: Thursday, March 19, 2020 11:33:43 AM
To: Hirter Hans
Cc: Sanchez David; Parker Althea (ID SIS); Wartenburger Richard (ID SIS)
Subject: Re: Datashot over VPN

Dear Hans,
Dear David,

Most probably the VM's firewall (or the VPZ) needs to be opened. Richard, here in cc., might be able to follow up with this as I'm not longer working for ID-SIS anymore.

Best Regards,

Cristian Scurtescu
ID BD
ETH Zurich
Weinbergstrasse 11 (WEC E 23)
8092 Zürich, Switzerland
+41 44 632 07 61

________________________________
From: Hirter Hans
Sent: Thursday, March 19, 2020 11:13 AM
To: Scurtescu Cristian (ID BD)
Cc: Sanchez David; Parker Althea (ID SIS)
Subject: Datashot over VPN

Dear Christian

David cannot use the Datashot application via VPN. The connection to the database is not working.
The Ento Coll DB can be reached directly via VPN. I tested it with MySQL Workbench over VPN. Can you please help David?
Here is the screenshot:
<image007.png>
There are Client connections over VPN:
<image008.png>

Best regards
Hans

Von: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>
Gesendet: Donnerstag, 19. März 2020 10:35
An: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Betreff: RE: Authorisierung IP- Adressen der VPN

Ich melde mich als ecdb an .

Im Anhang finden Sie die Eingaberesultate.

Gruss
David Sanchez

From: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Sent: Donnerstag, 19. März 2020 10:21
To: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>
Subject: AW: Authorisierung IP- Adressen der VPN

Hallo Herr Sanchez

Geben sie mal die folgenden Befehle in einem CMD Fenster ein:
ping entocoll.ethz.ch<http://entocoll.ethz.ch/>
ipconfig
Es sollte folgendes Resultat geben:
C:\Users\hirter>ping entocoll.ethz.ch<http://entocoll.ethz.ch/>

Ping wird ausgeführt für entocoll.ethz.ch<http://entocoll.ethz.ch/> [129.132.221.242] mit 32 Bytes Daten:
Antwort von 129.132.221.242: Bytes=32 Zeit=9ms TTL=59
Antwort von 129.132.221.242: Bytes=32 Zeit=9ms TTL=59
Antwort von 129.132.221.242: Bytes=32 Zeit=9ms TTL=59
Antwort von 129.132.221.242: Bytes=32 Zeit=11ms TTL=59

Ping-Statistik für 129.132.221.242:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 9ms, Maximum = 11ms, Mittelwert = 9ms

C:\Users\hirter>ipconfig

Windows-IP-Konfiguration


Ethernet-Adapter Ethernet 2:

   Verbindungsspezifisches DNS-Suffix: ethz.ch<http://ethz.ch/>
   IPv6-Adresse. . . . . . . . . . . : 2001:67c:10ec:578f:8000::479
   Verbindungslokale IPv6-Adresse  . : fe80::58b7:154f:be2d:7b83%14
   IPv4-Adresse  . . . . . . . . . . : 10.6.205.26
   Subnetzmaske  . . . . . . . . . . : 255.255.224.0
   Standardgateway . . . . . . . . . : ::
                                       10.6.192.1

Ethernet-Adapter Ethernet:

Noch eine Frage: mit welchem Benutzer verbinden sie sich mit der DB? Ist es ecdb?

Beste Grüsse
Hans Hirter


Von: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>
Gesendet: Donnerstag, 19. März 2020 09:30
An: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Betreff: RE: Authorisierung IP- Adressen der VPN

Hallo Herr Hirter

Ich habe Ihnen die AnyConnect Statistik angehängt.

Auf dem ersten Blick sieht es gut aus.

Allerdings habe ich gesehen, dass bei meinr Ethernet- Verbindung drei Ziffern am Anfang der IPv4 Adresse steht, könnte das der Grund sein?

Freundliche Grüsse
David Sanchez

From: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Sent: Donnerstag, 19. März 2020 09:20
To: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>
Subject: AW: Authorisierung IP- Adressen der VPN

Guten Tag Herr Sanchez

Bei mir sieht es folgendermassen aus:
Ich habe VPN gemacht und folgende IP erhalten: 10.6.205.0
<image009.png>

Verbindung zur EntoColl DB:
<image010.png>

Und hier noch die Details der Berechtigungen. Der Benutzer ecdb kann mit allen IP 10.x.x.x zugreifen.
<image011.png>

Haben sie eine VPN IP 10.x.x.x ?

Beste Grüsse
Hans Hirter

Von: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>
Gesendet: Donnerstag, 19. März 2020 08:46
An: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Cc: Greeff Michael <michael.greeff@usys.ethz.ch<mailto:michael.greeff@usys.ethz.ch>>
Betreff: RE: Authorisierung IP- Adressen der VPN

Guten Morgen Herr Hirter

Es scheint noch nicht zu funktionieren.

Ich habe es über dem Geschäftscomputer versucht.

Es verhält sich noch genau gleich.

Hat es bei Ihnen geklappt?

Muss ich evtl. Etwas an den Verbindungseinstellungen ändern?

Gruss
David Sanchez

From: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Sent: Mittwoch, 18. März 2020 18:26
To: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>
Cc: Greeff Michael <michael.greeff@usys.ethz.ch<mailto:michael.greeff@usys.ethz.ch>>
Subject: AW: Authorisierung IP- Adressen der VPN

Lieber Herr Sanchez

Können sie es bitte nochmals versuchen über VPN auf die DB zu zugreifen. Jetzt sollte es klappen.

Beste Grüsse
Hans Hirter

Von: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>
Gesendet: Mittwoch, 18. März 2020 16:12
An: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Cc: Greeff Michael <michael.greeff@usys.ethz.ch<mailto:michael.greeff@usys.ethz.ch>>
Betreff: FW: Authorisierung IP- Adressen der VPN

Ich meinte diese Datei im Anhang.

From: Sanchez David
Sent: Mittwoch, 18. März 2020 16:09
To: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Cc: 'Greeff Michael' <michael.greeff@usys.ethz.ch<mailto:michael.greeff@usys.ethz.ch>>
Subject: RE: Authorisierung IP- Adressen der VPN

Guten Tag Herr Hirter

Über ein Programm, es heisst Datashot.

Das Programm liest dafür das im Anhang befindliche Textfile um die richtige Verbindung zu wählen.

Allerdings scheint es über VPN nicht zu klappen.

Freundliche Grüsse
David Sanchez

From: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Sent: Mittwoch, 18. März 2020 16:01
To: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>
Subject: AW: Authorisierung IP- Adressen der VPN

Guten Tag Herr Sanchez

Mit VPN kriegen sie bei jeder neuen Verbindung immer eine andere Nummer.
Der Server entocoll.ethz.ch<http://entocoll.ethz.ch/> hat die IP Nummer 129.132.221.242 und ist über VPN erreichbar.
Ich habe es mit ping versucht:
C:\Users\hirter>ping 129.132.221.242

Ping wird ausgeführt für 129.132.221.242 mit 32 Bytes Daten:
Antwort von 129.132.221.242: Bytes=32 Zeit=9ms TTL=59
Antwort von 129.132.221.242: Bytes=32 Zeit=8ms TTL=59
Antwort von 129.132.221.242: Bytes=32 Zeit=9ms TTL=59
Antwort von 129.132.221.242: Bytes=32 Zeit=9ms TTL=59

Ping-Statistik für 129.132.221.242:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 8ms, Maximum = 9ms, Mittelwert = 8ms

C:\Users\hirter>

oder ssh:
[isg@isg-hest-242 ~]$ ifconfig
ens32: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 129.132.221.242  netmask 255.255.255.0  broadcast 129.132.221.255

Wie greifen Sie auf die DB Ento-Coll zu? Browser, Programm, … ?

Beste Grüsse
Hans Hirter



Von: Sanchez David <dsanchez@ethz.ch<mailto:dsanchez@ethz.ch>>
Gesendet: Mittwoch, 18. März 2020 15:28
An: Hirter Hans <hans.hirter@env.ethz.ch<mailto:hans.hirter@env.ethz.ch>>
Cc: Greeff Michael <michael.greeff@usys.ethz.ch<mailto:michael.greeff@usys.ethz.ch>>
Betreff: Authorisierung IP- Adressen der VPN

Guten Tag Herr Hirter,

Als ich versuchte, über meinen VPN- Zugang  die Applikation Datashot zu benutzen, misglückte mir die Verbindung zur Datenbank.

Wir vermuten, dass das VPN eine andere IP Adresse benutzt als der Computer, somit müsse diese IP- Adresse authorisiert werden, damit ich mit dem VPN Datashot benutzen kann.

Ich konnte mich auch an meinem privaten Rechner ins VPN einloggen, hat diese Verbindung eine separate IP- Adresse ? falls ja, wäre ich sehr dankbar wenn man diese ebenfalls hinzufügen würde.

Falls Sie mehr Informationen benötigen, lassen Sie es mich wissen.

Freundliche Grüsse
David Sanchez

**Comment by GenieTim** [comment]
Lieber David

Besten Dank für Deine Anfrage. Ich würde Dich bitten, mir diese E-Mail doch an meine private E-Mail-Adresse zu senden, wenn sie - so wie diese - einige private Informationen (IP, e-Mail Unbeteiligter, ...) enthalten, da dieses Repositorium öffentlich ist. Was das eigentliche Problem betrifft, werde ich es in den nächsten Tagen also nochmals etwas genauer ansehen und mich melden, wenn ich mehr weiss.

Beste Grüsse

Tim

**Comment by Commodore95** [comment]
Tim,

In Ordnung, ich bräuchte deine private E- Mail.

Dann sende ich dir nochmals das Mail.

Es ist etwas dringender, weil Michael Infos hat, dass wir demnächst eine komplette Karantäne in der Schweiz haben werden.

Der eine Zivi müsste den Geschäftsrechner von mir holen, aber nur unter der Prämisse, dass alles bereit ist.

Kannst du abschätzen wie lange du brauchst ? Wäre es dir möglich es noch morgen am Morgen zu bewerkstelligen?

Gruss
David

**Comment by GenieTim** [comment]
This issue should be resolved since yesterday evening: the new versions get now generated by GitHub actions instead of Travis, enabling the desired workflow. Pre-releases will therefore from now on get the version incremented before becoming a release, while releases will be distinguished by lacking the suffix `-SNAPSHOT` but keeping the version number.
