### ISSUE TITLE
Not able to delete Entries 

### ISSUE THREAD

**Issue by Commodore95** [BernhardWebstudio/DataShot_DesktopApp#30]
On all Version from 20200226 to the latest, there are issues with deleting entries such as collector or numbers and more. 

If you need more Information please let me know.

**Comment by GenieTim** [comment]
Yes, please some more details: when I delete those entries, I do not have issues either saving nor just add / readding them. What is it that I have to do to replicate the issue? Is there a certain error message popping up?

**Comment by Commodore95** [comment]
It was Julain who found it, so I forwarded him this E-Mail so that he can give you more details.

Sincerely,
david

**Comment by Commodore95** [comment]
Ok so:

In the latest version, we are just unable to delete entries in the "collectors" fields before saving.

Only after saving is a deletion possible.

Everything else works perfectly.

Let me know if you need more information.

Sincerely,
David

**Comment by GenieTim** [comment]
I unfortunately still cannot replicate this issue. Are we talking about 20200313-beta? 
Also, how do you realize sou cannot delete – is there an error message? Or, how far do you get: do you get to (a) the right-click "Delete Row" submenu, (b) the confirmation dialog?
Do you highlight the row clearly (-> green) before invoking the right-click menu?

**Comment by Commodore95** [comment]
Yes, we were talking about the 20200313-beta but somehow it is missing now the "releases" tab. 
The right-click "Delete Row" submenu did not pop up, as if it did not recognize the right-click event.

Yes, I highlighted the row before right-clicking.

However, in the 20200308-beta Version, it worked, so this seems to have solved itself.

Nevertheless, we appreciate your support.
