### ISSUE TITLE
Newest Datashot release not compatible with current database version, update not possible

### ISSUE THREAD

**Issue by Commodore95** [BernhardWebstudio/DataShot_DesktopApp#31]
Hi Tim,

I tried to test your newest release. 

Wenn logging in to the database, a message pops up suggesting that I may update the database to the current Version, when confirming the proposal I get an error message 

![image](https://user-images.githubusercontent.com/61057314/81792496-6da49100-9508-11ea-8ed5-82f26cf41ed5.png)

**Comment by GenieTim** [comment]
I see, this is still the problem we had since #21, that the MySQL (MariaDB) version is too old. I thankfully have remote access now so that I can update the database structure (not the version unfortunately) remotly. It might be fixed now?

**Comment by Commodore95** [comment]
Yes it is, thank you!
