### ISSUE TITLE
Extend search mask to filter by "Last updated Date"

### ISSUE THREAD

**Issue by yvessavoy** [BernhardWebstudio/DataShot_DesktopApp#32]
This would be helpful so we can filter with our own name and the date to know how many entries we made that day and / or to check how many entries we've done today. It should filter on the timestamp shown in the "Last edit date"-Field

**Comment by GenieTim** [comment]
Thanks for the feedback. What type of input would you consider the best:

1. Range selection: enter two dates with time to get all Specimen with a DateLastUpdated in between the two input dates
2. One input only: before: get all Specimen with DateLastUpdated before the input date
3. One input only: after: get all Specimen with DateLastUpdated after the input date
4. One input only: exact: get the Specimen with the exact value of DateLastUpdated
5. One input only: day: input a date without time, get all Specimen with DateLastUpdated on the same as the input date
6. Something else?

**Comment by yvessavoy** [comment]
@GenieTim I guess option 5 is the one that would help us the most. We can enter a date, i.e. 22.01.2021 and it should show me all entries that have been last updated on this date.

**Comment by GenieTim** [comment]
Should be testable in https://github.com/BernhardWebstudio/DataShot_DesktopApp/releases/tag/untagged-DataShot-20210125-1506-beta-d5c5ed2da30f6607d7ee42d41c573a5669f8ef28

**Comment by yvessavoy** [comment]
Seems to be working, thanks. However, when I entered a date and then delete it again after searching, I can clear the field but as soon as I press Search, the date reappears and it only searches for entries with that date even tho I deleted it. We can work around it by opening a new search dialog, it's just a bit annoying.
