### ISSUE TITLE
Wrong names with auto-fill when entering Lat/Long

### ISSUE THREAD

**Issue by EntomologicalZivi** [BernhardWebstudio/DataShot_DesktopApp#34]
We use this excel table to determine the correct names. The correct names of the countries are in column A. The correct names of the provinces are in column B.

[Countries_primary_divisions_ISO3166_xls.xlsx](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/5902829/Countries_primary_divisions_ISO3166_xls.xlsx)

Do you want me to put only wrong names in the .csv list or all of them?

**Comment by GenieTim** [comment]
Excel is fine too. I just need some way to know what wrong to replace with what right. So, e.g. one column "wrong" and one column "right". Or similar.

**Comment by EntomologicalZivi** [comment]
Ok. So as i said the column A and B are always "right". And in column C i put the "wrong" names.
Right now we know of only six wrong names, but we have to use them a lot.

[Countries_primary_divisions_TIM.xlsx](https://github.com/BernhardWebstudio/DataShot_DesktopApp/files/5909644/Countries_primary_divisions_TIM.xlsx)

We'll keep you updated if more come along.

**Comment by EntomologicalZivi** [comment]
I've made a Goole-Sheets file out of it. Is that ok?
You could just delete our wrong names in the column C when you updated them.
Like this we would always be up to date and won't have to send files around.

The sheet:
https://docs.google.com/spreadsheets/d/19Z4SiynHQmaoLqqz2SgMpOn-EcZim333hWq-Oov90g8/edit?usp=sharing
