### ISSUE TITLE
Copy from previous: Attributes not copied

### ISSUE THREAD

**Issue by greeffm** [BernhardWebstudio/DataShot_DesktopApp#35]
When using "copy from previous", the following information is lost: Attributes. The attributes field is filled in by clicking on the "Edit" button in the section "Specimen Parts" (see screenshot). By doing so, the user has the option to select an Attribute type and a Caste. These two values are lost when using "copy from previous".
<img width="1025" alt="Screenshot 2021-02-02 at 10 52 17" src="https://user-images.githubusercontent.com/54636901/106584032-03c09180-6546-11eb-8b2c-6fa9b10890a2.png">

**Comment by GenieTim** [comment]
This issue should be fixed in https://github.com/BernhardWebstudio/DataShot_DesktopApp/releases/tag/untagged-DataShot-20210202-1224-beta-4e640abe78604c204f35e6dfdf6503a56f99e7f3
Feel free to re-open this issue if you still encounter this error in the new version.
