### ISSUE TITLE
Errors when pasting coordinates

### ISSUE THREAD

**Issue by dvn0813** [BernhardWebstudio/DataShot_DesktopApp#41]
If the number of decimal places exceeds 5, the longitude coordinate will not be registered or pasted with a blank space before the coordinate. 
DataShot-20210816-0939-beta was used

**Comment by GenieTim** [comment]
Thanks for the report. Unfortunately, I cannot quite replicate your issue (see screencast below). Can you expand a bit further whether you paste from excel/Google Sheets or just into one field, and whether you paste in the main or the Georef dialog? And do you happen to have an example Excel-Row and Specimen I could use for easier replication?


https://user-images.githubusercontent.com/8596965/130050866-44941908-683c-4802-9efc-5797a5b4a90c.mov

**Comment by dvn0813** [comment]
---------- Forwarded message ---------
Von: Dave n ***@***.***>
Date: Fr., 20. Aug. 2021, 09:38
Subject: Re: [BernhardWebstudio/DataShot_DesktopApp] Errors when pasting
coordinates (#41)
To: BernhardWebstudio/DataShot_DesktopApp <
***@***.***>


Dear Tim Bernhard

Thank you for your E-mail.
My assumption was wrong. The problem is that the blank space in front of
the longitude coordinate of some locations is not the usual blank space.
This would be the case with the location "Davos". I am not sure if many
locations are affected by this.
When you paste the coordinates into word, the blank space is represented by
an empty circle instead of a dot.
As it is a minor problem affecting only certain excel entries there is no
need to change anything about the program.

Thank you for your time.
Best regards
David Niu

Tim Bernhard ***@***.***> schrieb am Do., 19. Aug. 2021,
12:10:

**Comment by GenieTim** [comment]
Dear David Niu,

I see. No worries. I will close this issue for now, but if you happen to have more than just this case where it fails, feel free to reopen the issue and I will gladly implement a solution into DataShot.

Best,

Tim
